[package]
name = "ark-ingest"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ark-core = { path = "../ark-core" }
async-trait.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true

